import Head from "next/head";
// import Image from "next/image";
import { FC } from "react";

import { DarkModeHoverMenu } from "../DarkModeHoverMenu";
import { NavMenu } from "../NavBar/NavMenu";

// import { NavBar } from "../NavBar";

export const HomeContent: FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <NavBar />

      <div className="w-64 text-right">
        <DarkModeHoverMenu />
      </div>

      <div className="w-64 text-right">
        <HoverMenuSimpleExample />
      </div>

      <HelloWorld /> */}

      <div className="flex w-32 flex-col sm:flex-row">
        <NavMenu />
        <NavMenu />
        <NavMenu />
      </div>
      <DarkModeHoverMenu />

      <main className="px-64">
        <h1 className="text-4xl font-bold">
          <span className="text-gray-700">Hello</span>
          <span className="text-gray-500">World</span>
        </h1>
        <p className="text-gray-700">
          Do adipisicing reprehenderit ad mollit consectetur laboris. Velit
          pariatur exercitation cupidatat voluptate anim id anim aliquip nulla
          voluptate. Ut commodo nostrud deserunt dolor aliqua et aliquip magna
          est sunt ipsum tempor fugiat quis. Laborum ipsum amet enim consectetur
          id sit eu veniam elit. Aliquip labore laboris adipisicing commodo sit
          Lorem eiusmod nostrud cillum laboris ad ad. Occaecat amet eu nulla et
          magna nulla aute ipsum. Do laborum aute pariatur consequat occaecat
          velit esse labore. Id dolore do irure laborum aliquip veniam et
          proident. Lorem officia quis eu do. Aliquip voluptate voluptate
          consequat ex enim deserunt. Velit do consectetur esse adipisicing
          voluptate nulla minim magna quis incididunt consequat. Velit et
          ullamco excepteur Lorem quis minim do irure ad magna incididunt ea
          fugiat. Minim officia culpa culpa ullamco veniam anim pariatur irure
          cillum. Officia duis dolore dolore ut aliqua quis velit laborum qui
          Lorem. Proident officia id veniam anim nisi.
        </p>
        <p className="text-gray-700">
          Adipisicing cupidatat minim pariatur aliquip anim sunt ad eiusmod
          tempor nulla qui est. Reprehenderit tempor laboris enim ex quis
          adipisicing pariatur. Enim amet ullamco ut eiusmod laboris sunt sit.
          Reprehenderit officia dolore ipsum cillum. Ea quis consectetur mollit
          sit ad cillum occaecat nisi quis deserunt. Labore id tempor culpa
          occaecat sint dolore est ex in eiusmod sint dolore id occaecat.
          Consequat irure officia consectetur ipsum in ullamco nulla magna
          reprehenderit ex eu aute. Est sit in fugiat Lorem. Consequat est
          commodo laboris sunt. Esse ea et velit amet ex. Dolor est sunt
          adipisicing magna sunt nulla consectetur qui. Elit aute laborum in
          esse aliquip proident adipisicing anim laborum irure et labore. Qui
          tempor sunt tempor aute elit aute incididunt et excepteur incididunt.
          Enim aliqua cupidatat tempor pariatur aliqua proident deserunt nisi
          esse quis aute aliqua esse. Velit id mollit tempor commodo aliquip
          occaecat elit cupidatat. Id pariatur commodo sit est laboris culpa
          amet anim tempor aute ad ea non. Pariatur non aute cillum ea nostrud
          velit cillum reprehenderit voluptate. Esse voluptate occaecat
          incididunt tempor culpa.
        </p>
      </main>
    </div>
  );
};
